### ISSUE TITLE
LICENSE is nonoptimal for some projects 

### ISSUE THREAD

**Issue by todb-r7** [unicornsasfuel/cryptanalib#1]
I'd like to convince you to license this as BSD instead of GPLv3, if you're receptive to the idea. As a GPLv3 project, it's difficult to incorporate cryptanalib into other projects as is.

**Comment by unicornsasfuel** [comment]
I'm most definitely open to this idea, but I may be bound by my employment agreement with my employer. I'll look into both the BSD license and my employment agreement.

**Comment by todb-r7** [comment]
Sweet, thanks!

I hate having to review case law just to contribute to a project I like.

**Comment by unicornsasfuel** [comment]
Switching to BSD license.

**Comment by todb-r7** [comment]
Sweet, you're my hero!

--
Sent from a tiny computer

On Apr 13, 2016, at 14:02, unicornsasfuel <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1<https://github.com/unicornsasfuel/cryptanalib/issues/1>.

-
